# Generated by Django 5.0.1 on 2024-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField()),
                ('driver_name', models.CharField(max_length=128)),
                ('start_time', models.TimeField()),
                ('commentary', models.TextField(blank=True, max_length=256, null=True)),
                ('client_list', models.TextField(choices=[('ТД Гроуми', 'ТД Гроуми')], max_length=256)),
                ('dispatcher', models.CharField(choices=[('Ксения Майорова', 'Ксения Майорова'), ('Мазалов Максим', 'Мазалов Максим'), ('Тольев Алексей', 'Тольев Алексей'), ('Анна Нуруллова', 'Анна Нуруллова')], max_length=128)),
            ],
        ),
    ]
