# Generated by Django 5.0.3 on 2024-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0001_initial'),
        ('manager_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryreport',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='deliveryreport',
            name='start_time',
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='dispatcher',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='EmailReportToClientSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=128)),
                ('message', models.TextField(blank=True, max_length=2048, null=True)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('clients', models.ManyToManyField(to='manager_client.client')),
            ],
        ),
    ]
