# Generated by Django 5.0.1 on 2024-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0002_remove_deliveryreport_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreport',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
