# Generated by Django 5.0.3 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0002_remove_deliveryreport_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(choices=[], max_length=256),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='dispatcher',
            field=models.CharField(choices=[('Ксения Майорова', 'Ксения Майорова'), ('Мазалов Максим', 'Мазалов Максим'), ('Тольев Алексей', 'Тольев Алексей'), ('Анна Нуруллова', 'Анна Нуруллова')], max_length=128),
        ),
    ]
