# Generated by Django 5.0.1 on 2024-02-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0003_deliveryreport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
