# Generated by Django 5.0.1 on 2024-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0004_alter_deliveryreport_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReportToClientSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ТД Гроуми', 'ТД Гроуми'), ('Ярославский Бройлер', 'Ярославский Бройлер'), ('Останкино Новый Стандарт', 'Останкино Новый Стандарт'), ('Шпинат', 'Шпинат'), ('тест', 'тест'), ('тестпочты', 'тестпочты')], max_length=128)),
                ('direction', models.CharField(max_length=128)),
                ('message', models.TextField(blank=True, max_length=1024, null=True)),
                ('email', models.EmailField(choices=[(None, None), ('ybroiler@broiler.com', 'ybroiler@broiler.com'), ('ost@ost.ru', 'ost@ost.ru'), ('shpinat@mail.ru', 'shpinat@mail.ru'), ('test@mail.ru', 'test@mail.ru'), ('serejka50@gmail.com', 'serejka50@gmail.com')], max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(choices=[('ТД Гроуми', 'ТД Гроуми'), ('Ярославский Бройлер', 'Ярославский Бройлер'), ('Останкино Новый Стандарт', 'Останкино Новый Стандарт'), ('Шпинат', 'Шпинат'), ('тест', 'тест'), ('тестпочты', 'тестпочты')], max_length=256),
        ),
    ]
