# Generated by Django 5.0.1 on 2024-02-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0005_emailreporttoclientsuccess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreporttoclientsuccess',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
