# Generated by Django 5.0.1 on 2024-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0006_alter_emailreporttoclientsuccess_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreporttoclientsuccess',
            name='email',
            field=models.CharField(choices=[(None, None), ('ybroiler@broiler.com', 'ybroiler@broiler.com'), ('ost@ost.ru', 'ost@ost.ru'), ('shpinat@mail.ru', 'shpinat@mail.ru'), ('test@mail.ru', 'test@mail.ru'), ('serejka50@gmail.com', 'serejka50@gmail.com')], max_length=128),
        ),
    ]
