# Generated by Django 5.0.1 on 2024-02-21 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0007_alter_emailreporttoclientsuccess_email'),
        ('manager_client', '0004_alter_client_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreporttoclientsuccess',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailreporttoclientsuccess',
            name='name',
        ),
        migrations.AddField(
            model_name='emailreporttoclientsuccess',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_client.client'),
        ),
    ]
