# Generated by Django 5.0.1 on 2024-02-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0008_remove_emailreporttoclientsuccess_email_and_more'),
        ('manager_client', '0004_alter_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreport',
            name='client_list',
            field=models.TextField(choices=[('ТД Гроуми', 'ТД Гроуми'), ('Ярославский Бройлер', 'Ярославский Бройлер'), ('Останкино Новый Стандарт', 'Останкино Новый Стандарт'), ('Шпинат', 'Шпинат'), ('тест', 'тест'), ('тестпочты', 'тестпочты'), ('тестпочты2', 'тестпочты2')], max_length=256),
        ),
        migrations.RemoveField(
            model_name='emailreporttoclientsuccess',
            name='client',
        ),
        migrations.AddField(
            model_name='emailreporttoclientsuccess',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='manager_client.client'),
        ),
    ]
