# Generated by Django 5.0.1 on 2024-02-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0009_alter_deliveryreport_client_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailreporttoclientsuccess',
            old_name='client',
            new_name='clients',
        ),
    ]
