# Generated by Django 5.0.1 on 2024-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0010_rename_client_emailreporttoclientsuccess_clients'),
        ('manager_client', '0004_alter_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailreporttoclientsuccess',
            name='clients',
            field=models.ManyToManyField(to='manager_client.client'),
        ),
    ]
