# Generated by Django 5.0.1 on 2024-02-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0011_alter_emailreporttoclientsuccess_clients'),
        ('manager_client', '0004_alter_client_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreporttoclientsuccess',
            name='date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='emailreporttoclientsuccess',
            name='message',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.CreateModel(
            name='ProblemEmailReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=2048, null=True)),
                ('email_to_send', models.EmailField(max_length=128)),
                ('clients', models.ManyToManyField(to='manager_client.client')),
            ],
        ),
    ]
