# Generated by Django 5.0.1 on 2024-02-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_report', '0012_emailreporttoclientsuccess_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemEmailReport',
        ),
    ]
