# Generated by Django 5.0.3 on 2024-03-05 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDriverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('org_name', models.CharField(max_length=128, null=True)),
                ('other_data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='driver_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
            ],
        ),
    ]
