# Generated by Django 5.0 on 2023-12-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddriverdata',
            name='phone',
        ),
        migrations.AddField(
            model_name='uploaddriverdata',
            name='org_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
