# Generated by Django 5.0 on 2024-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0002_remove_uploaddriverdata_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddriverdata',
            name='files_2',
            field=models.FileField(blank=True, null=True, upload_to='driver_data/'),
        ),
    ]
