# Generated by Django 5.0 on 2024-01-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0003_uploaddriverdata_files_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddriverdata',
            name='files_2',
        ),
    ]
