# Generated by Django 5.0 on 2024-01-09 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0004_remove_uploaddriverdata_files_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_num', models.CharField(max_length=48)),
                ('trailer_name', models.CharField(max_length=24, null=True)),
                ('trailer_number', models.CharField(max_length=48, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scan_doc', models.FileField(blank=True, null=True, upload_to='car_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])])),
            ],
        ),
        migrations.AlterField(
            model_name='uploaddriverdata',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='driver_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
