# Generated by Django 5.0 on 2024-01-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0005_uploadcardata_alter_uploaddriverdata_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadcardata',
            old_name='car_num',
            new_name='car_number',
        ),
    ]
