# Generated by Django 5.0 on 2024-01-12 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_driver_data', '0007_delete_uploadcardata_alter_uploaddriverdata_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddriverdata',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='driver_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
