# Generated by Django 5.0.1 on 2024-02-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_client', '0002_remove_client_tag_remove_client_inn_client_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='main_email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
