# Generated by Django 5.0.1 on 2024-02-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_client', '0003_client_main_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='manager',
            field=models.CharField(blank=True, choices=[('Владимир Сороковой', 'Владимир Сороковой'), ('Наталья Пряхина', 'Наталья Пряхина'), ('Татьяна Петкун', 'Татьяна Петкун'), ('Марта Селиксар', 'Марта Селиксар'), ('Ольга Лаппо', 'Ольга Лаппо'), ('Екатерина Смышлякова', 'Екатерина Смышлякова'), ('Анастасия Тарассу', 'Анастасия Тарассу'), ('Алексей Зайцев', 'Алексей Зайцев'), ('Всеволод Родионов', 'Всеволод Родионов'), ('Перминова Надежда', 'Перминова Надежда'), ('Менедежры УК Грандо', 'Менедежры УК Грандо')], max_length=128, null=True),
        ),
    ]
